version: "3.9"

services:
    web-log:
      image: devopsdockeruh/simple-web-service
      ports:
        - 8000:8000
      command: docker run -d devopsdockeruh/simple-web-service 
      container_name: web-log
